//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_News_Likes
    {
        public int Id { get; set; }
        public int NewsId { get; set; }
        public string UserIp { get; set; }
        public bool Like { get; set; }
        public bool Dislike { get; set; }
    
        public virtual Tbl_News Tbl_News { get; set; }
    }
}
