//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Psw { get; set; }
        public string Email { get; set; }
        public string Access { get; set; }
        public string Discription { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Ncode { get; set; }
        public string Mobnumber { get; set; }
        public bool Enable { get; set; }
        public System.DateTime DateRegistration { get; set; }
    }
}
