//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comment
    {
        public int Id { get; set; }
        public int NewsId { get; set; }
        public int ParentId { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Text { get; set; }
        public string Ip { get; set; }
        public System.DateTime Date { get; set; }
        public bool Confirm { get; set; }
        public bool Read { get; set; }
        public int Like { get; set; }
        public int Dislike { get; set; }
    
        public virtual Tbl_News Tbl_News { get; set; }
    }
}
