//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Setting
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Discription { get; set; }
        public string MetaTage { get; set; }
        public bool ShowConfComm { get; set; }
        public bool DisableComment { get; set; }
        public string MaxUploadSize { get; set; }
        public int CountNewsInPage { get; set; }
        public int CountOfMemo { get; set; }
        public int CountNewer { get; set; }
        public int CountPopular { get; set; }
    }
}
