//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_News()
        {
            this.Tbl_Comment = new HashSet<Tbl_Comment>();
            this.Tbl_News_Likes = new HashSet<Tbl_News_Likes>();
            this.Tbl_R_News_Cat = new HashSet<Tbl_R_News_Cat>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string HeadTitle { get; set; }
        public string Text { get; set; }
        public string FullText { get; set; }
        public string Imge { get; set; }
        public long Visit { get; set; }
        public int Like { get; set; }
        public int DisLike { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Comment> Tbl_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_News_Likes> Tbl_News_Likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_R_News_Cat> Tbl_R_News_Cat { get; set; }
    }
}
